kind: Service
apiVersion: v1
metadata:
  name: hf-tgi-server
  labels:
    app: hf-tgi-server
spec:
  clusterIP: None
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: hf-tgi-server
